-- ============================================================
-- Industry × Venue Type — Share of venue types by industry
-- ============================================================
-- SOURCE: Snowflake — BOOKING_LINES + VENUES + COMPANIES + HUBSPOT.COMPANIES
-- NOTE:   Uses ALL bookings (not just confirmed/CONTRACT), per user request
-- JOIN:   BOOKING_LINES.VENUEID → VENUES.VENUEID (integer)
--         BOOKING_LINES.COMPANYDATA___ID → COMPANIES._ID → HUBSPOTID → HUBSPOT.COMPANIES.HS_OBJECT_ID
-- VENUE TYPES: Boolean columns on VENUES table (VENUETYPES__RESTAURANT, etc.)
--              Unpivoted via UNION ALL since Snowflake doesn't support LATERAL
-- PERIODS: BEFORE = 2022–2023, AFTER = 2024–2025
-- DATE:   26 March 2026
-- RESULTS: js/data.js → DATA.venueTypesByIndustry

-- ── QUERY 1: Total booking lines per industry per period (for computing shares) ──

SELECT
    CASE
        WHEN hc.INDUSTRY IN ('ACCOUNTING','BANKING___MORTGAGE','CAPITAL_MARKETS','FINANCIAL_SERVICES','INSURANCE','VENTURE_CAPITAL___PRIVATE_EQUITY') THEN 'Financial Services'
        WHEN hc.INDUSTRY IN ('INFORMATION_TECHNOLOGY___SERVICES','COMPUTER_SOFTWARE','INTERNET','COMPUTER_HARDWARE','COMPUTER___NETWORK_SECURITY','COMPUTER_GAMES','SEMICONDUCTORS','TELECOMMUNICATIONS','WIRELESS') THEN 'Technology'
        WHEN hc.INDUSTRY IN ('MARKETING___ADVERTISING','MEDIA_PRODUCTION','ENTERTAINMENT','BROADCAST_MEDIA','MUSIC','MOTION_PICTURES___FILM','PUBLISHING','NEWSPAPERS','ONLINE_MEDIA','PRINTING') THEN 'Media & Marketing'
        WHEN hc.INDUSTRY IN ('LAW_PRACTICE','MANAGEMENT_CONSULTING','HUMAN_RESOURCES','STAFFING___RECRUITING','PROFESSIONAL_TRAINING___COACHING','BUSINESS_SUPPLIES___EQUIPMENT','OUTSOURCING_OFFSHORING','EXECUTIVE_OFFICE','PROGRAM_DEVELOPMENT','THINK_TANKS','TRANSLATION___LOCALIZATION') THEN 'Professional Services'
        WHEN hc.INDUSTRY IN ('HOSPITAL___HEALTH_CARE','MEDICAL_DEVICES','PHARMACEUTICALS','HEALTH__WELLNESS___FITNESS','MENTAL_HEALTH_CARE','VETERINARY','BIOTECHNOLOGY','ALTERNATIVE_MEDICINE','MEDICAL_PRACTICE') THEN 'Healthcare & Pharma'
        WHEN hc.INDUSTRY IN ('RETAIL','CONSUMER_GOODS','CONSUMER_ELECTRONICS','CONSUMER_SERVICES','LUXURY_GOODS___JEWELRY','FOOD___BEVERAGES','WINE___SPIRITS','COSMETICS','APPAREL___FASHION','FURNITURE','SPORTING_GOODS','SUPERMARKETS','WHOLESALE','PACKAGE_FREIGHT_DELIVERY') THEN 'Retail & Consumer'
        WHEN hc.INDUSTRY IN ('CONSTRUCTION','REAL_ESTATE','ARCHITECTURE___PLANNING','BUILDING_MATERIALS','CIVIL_ENGINEERING') THEN 'Property & Construction'
        WHEN hc.INDUSTRY IN ('LEISURE__TRAVEL___TOURISM','HOSPITALITY','AIRLINES_AVIATION','RESTAURANTS','FOOD_PRODUCTION','RECREATIONAL_FACILITIES___SERVICES','GAMBLING___CASINOS','SPORTS') THEN 'Travel & Leisure'
        WHEN hc.INDUSTRY IN ('EDUCATION_MANAGEMENT','E_LEARNING','HIGHER_EDUCATION','PRIMARY_SECONDARY_EDUCATION','RESEARCH','LIBRARIES') THEN 'Education & Training'
        ELSE NULL
    END AS industry_group,
    CASE WHEN YEAR(bl."META__CREATEDAT") IN (2022, 2023) THEN 'before' ELSE 'after' END AS period,
    COUNT(*) AS cnt
FROM HIRE_SPACE.CORE_DATA.BOOKING_LINES bl
JOIN HIRE_SPACE.CORE_DATA.COMPANIES c ON c."_ID" = bl."COMPANYDATA___ID"
JOIN SEGMENT_EVENTS.HUBSPOT.COMPANIES hc ON hc.HS_OBJECT_ID = c.HUBSPOTID
WHERE YEAR(bl."META__CREATEDAT") BETWEEN 2022 AND 2025
  AND hc.INDUSTRY IS NOT NULL
GROUP BY 1, 2
HAVING industry_group IS NOT NULL;


-- ── QUERY 2: Venue type counts per industry per period ──
-- Generated dynamically in Python as 23 UNION ALL branches.
-- One branch per venue type boolean column on VENUES table.
-- Example for RESTAURANT (repeat for each type):

SELECT
    CASE
        WHEN hc.INDUSTRY IN ('ACCOUNTING','BANKING___MORTGAGE','CAPITAL_MARKETS','FINANCIAL_SERVICES','INSURANCE','VENTURE_CAPITAL___PRIVATE_EQUITY') THEN 'Financial Services'
        WHEN hc.INDUSTRY IN ('INFORMATION_TECHNOLOGY___SERVICES','COMPUTER_SOFTWARE','INTERNET','COMPUTER_HARDWARE','COMPUTER___NETWORK_SECURITY','COMPUTER_GAMES','SEMICONDUCTORS','TELECOMMUNICATIONS','WIRELESS') THEN 'Technology'
        WHEN hc.INDUSTRY IN ('MARKETING___ADVERTISING','MEDIA_PRODUCTION','ENTERTAINMENT','BROADCAST_MEDIA','MUSIC','MOTION_PICTURES___FILM','PUBLISHING','NEWSPAPERS','ONLINE_MEDIA','PRINTING') THEN 'Media & Marketing'
        WHEN hc.INDUSTRY IN ('LAW_PRACTICE','MANAGEMENT_CONSULTING','HUMAN_RESOURCES','STAFFING___RECRUITING','PROFESSIONAL_TRAINING___COACHING','BUSINESS_SUPPLIES___EQUIPMENT','OUTSOURCING_OFFSHORING','EXECUTIVE_OFFICE','PROGRAM_DEVELOPMENT','THINK_TANKS','TRANSLATION___LOCALIZATION') THEN 'Professional Services'
        WHEN hc.INDUSTRY IN ('HOSPITAL___HEALTH_CARE','MEDICAL_DEVICES','PHARMACEUTICALS','HEALTH__WELLNESS___FITNESS','MENTAL_HEALTH_CARE','VETERINARY','BIOTECHNOLOGY','ALTERNATIVE_MEDICINE','MEDICAL_PRACTICE') THEN 'Healthcare & Pharma'
        WHEN hc.INDUSTRY IN ('RETAIL','CONSUMER_GOODS','CONSUMER_ELECTRONICS','CONSUMER_SERVICES','LUXURY_GOODS___JEWELRY','FOOD___BEVERAGES','WINE___SPIRITS','COSMETICS','APPAREL___FASHION','FURNITURE','SPORTING_GOODS','SUPERMARKETS','WHOLESALE','PACKAGE_FREIGHT_DELIVERY') THEN 'Retail & Consumer'
        WHEN hc.INDUSTRY IN ('CONSTRUCTION','REAL_ESTATE','ARCHITECTURE___PLANNING','BUILDING_MATERIALS','CIVIL_ENGINEERING') THEN 'Property & Construction'
        WHEN hc.INDUSTRY IN ('LEISURE__TRAVEL___TOURISM','HOSPITALITY','AIRLINES_AVIATION','RESTAURANTS','FOOD_PRODUCTION','RECREATIONAL_FACILITIES___SERVICES','GAMBLING___CASINOS','SPORTS') THEN 'Travel & Leisure'
        WHEN hc.INDUSTRY IN ('EDUCATION_MANAGEMENT','E_LEARNING','HIGHER_EDUCATION','PRIMARY_SECONDARY_EDUCATION','RESEARCH','LIBRARIES') THEN 'Education & Training'
        ELSE NULL
    END AS industry_group,
    'RESTAURANT' AS venue_type,
    CASE WHEN YEAR(bl."META__CREATEDAT") IN (2022, 2023) THEN 'before' ELSE 'after' END AS period,
    COUNT(*) AS cnt
FROM HIRE_SPACE.CORE_DATA.BOOKING_LINES bl
JOIN HIRE_SPACE.CORE_DATA.VENUES v ON v.VENUEID = bl.VENUEID
JOIN HIRE_SPACE.CORE_DATA.COMPANIES c ON c."_ID" = bl."COMPANYDATA___ID"
JOIN SEGMENT_EVENTS.HUBSPOT.COMPANIES hc ON hc.HS_OBJECT_ID = c.HUBSPOTID
WHERE v."VENUETYPES__RESTAURANT" = TRUE
  AND YEAR(bl."META__CREATEDAT") BETWEEN 2022 AND 2025
  AND hc.INDUSTRY IS NOT NULL
GROUP BY 1, 2, 3
HAVING industry_group IS NOT NULL

UNION ALL

-- ... repeat for each venue type boolean column:
-- HOTEL, BAR, ROOFTOP, HISTORICBUILDINGSLANDMARK, CONFERENCECENTRE,
-- EVENTVENUE, MEETINGROOMSCOWORKING, GALLERY, CINEMA, THEATRE,
-- WAREHOUSE, OUTDOOR, BOAT, SPORTINGVENUE, PUB, NIGHTCLUB,
-- ACTIVITYBAR, ACTIVITYVENUE, BREWERYDISTILLERY, SOCIALGAME,
-- GARDENCONSERVATORY, MUSEUM

-- ── Venue type column names (from INFORMATION_SCHEMA) ──
-- VENUETYPES__RESTAURANT, VENUETYPES__HOTEL, VENUETYPES__BAR,
-- VENUETYPES__ROOFTOP, VENUETYPES__HISTORICBUILDINGSLANDMARK,
-- VENUETYPES__CONFERENCECENTRE, VENUETYPES__EVENTVENUE,
-- VENUETYPES__MEETINGROOMSCOWORKING, VENUETYPES__GALLERY,
-- VENUETYPES__CINEMA, VENUETYPES__THEATRE, VENUETYPES__WAREHOUSE,
-- VENUETYPES__OUTDOOR, VENUETYPES__BOAT, VENUETYPES__SPORTINGVENUE,
-- VENUETYPES__PUB, VENUETYPES__NIGHTCLUB, VENUETYPES__ACTIVITYBAR,
-- VENUETYPES__ACTIVITYVENUE, VENUETYPES__BREWERYDISTILLERY,
-- VENUETYPES__SOCIALGAME, VENUETYPES__GARDENCONSERVATORY,
-- VENUETYPES__MUSEUM

-- ── Post-processing (Python) ──
-- For each industry:
--   share = venue_type_count / industry_total * 100
--   change = after_share - before_share
-- Top 4 gaining (change > 0, sorted desc) and top 3 declining (change < 0, sorted asc)
-- Threshold: personalisation only applied if top gaining change >= 1.0pp
