-- ============================================================
-- Industry × Event Type — Share of event categories by industry
-- ============================================================
-- SOURCE: Snowflake — BOOKINGS + COMPANIES + HUBSPOT.COMPANIES
-- NOTE:   Uses ALL bookings (not just won), per user request
-- JOIN:   BOOKINGS.COMPANYDATA___ID → COMPANIES._ID → HUBSPOTID → HUBSPOT.COMPANIES.HS_OBJECT_ID
-- EVENT TYPE: BOOKINGS.CATEGORY (e.g. 'category-conference', 'category-meeting')
-- PERIODS: BEFORE = 2022–2023, AFTER = 2024–2025
-- UPDATED: 27 March 2026 — switched from BOOKING_LINES to BOOKINGS
-- RESULTS: js/data.js → DATA.eventTypesByIndustry

-- ── QUERY: Event category counts per industry per period ──

SELECT
    CASE
        WHEN hc.INDUSTRY IN ('ACCOUNTING','BANKING___MORTGAGE','CAPITAL_MARKETS','FINANCIAL_SERVICES','INSURANCE','VENTURE_CAPITAL___PRIVATE_EQUITY') THEN 'Financial Services'
        WHEN hc.INDUSTRY IN ('INFORMATION_TECHNOLOGY___SERVICES','COMPUTER_SOFTWARE','INTERNET','COMPUTER_HARDWARE','COMPUTER___NETWORK_SECURITY','COMPUTER_GAMES','SEMICONDUCTORS','TELECOMMUNICATIONS','WIRELESS') THEN 'Technology'
        WHEN hc.INDUSTRY IN ('MARKETING___ADVERTISING','MEDIA_PRODUCTION','ENTERTAINMENT','BROADCAST_MEDIA','MUSIC','MOTION_PICTURES___FILM','PUBLISHING','NEWSPAPERS','ONLINE_MEDIA','PRINTING') THEN 'Media & Marketing'
        WHEN hc.INDUSTRY IN ('LAW_PRACTICE','MANAGEMENT_CONSULTING','HUMAN_RESOURCES','STAFFING___RECRUITING','PROFESSIONAL_TRAINING___COACHING','BUSINESS_SUPPLIES___EQUIPMENT','OUTSOURCING_OFFSHORING','EXECUTIVE_OFFICE','PROGRAM_DEVELOPMENT','THINK_TANKS','TRANSLATION___LOCALIZATION') THEN 'Professional Services'
        WHEN hc.INDUSTRY IN ('HOSPITAL___HEALTH_CARE','MEDICAL_DEVICES','PHARMACEUTICALS','HEALTH__WELLNESS___FITNESS','MENTAL_HEALTH_CARE','VETERINARY','BIOTECHNOLOGY','ALTERNATIVE_MEDICINE','MEDICAL_PRACTICE') THEN 'Healthcare & Pharma'
        WHEN hc.INDUSTRY IN ('RETAIL','CONSUMER_GOODS','CONSUMER_ELECTRONICS','CONSUMER_SERVICES','LUXURY_GOODS___JEWELRY','FOOD___BEVERAGES','WINE___SPIRITS','COSMETICS','APPAREL___FASHION','FURNITURE','SPORTING_GOODS','SUPERMARKETS','WHOLESALE','PACKAGE_FREIGHT_DELIVERY') THEN 'Retail & Consumer'
        WHEN hc.INDUSTRY IN ('CONSTRUCTION','REAL_ESTATE','ARCHITECTURE___PLANNING','BUILDING_MATERIALS','CIVIL_ENGINEERING') THEN 'Property & Construction'
        WHEN hc.INDUSTRY IN ('LEISURE__TRAVEL___TOURISM','HOSPITALITY','AIRLINES_AVIATION','RESTAURANTS','FOOD_PRODUCTION','RECREATIONAL_FACILITIES___SERVICES','GAMBLING___CASINOS','SPORTS') THEN 'Travel & Leisure'
        WHEN hc.INDUSTRY IN ('EDUCATION_MANAGEMENT','E_LEARNING','HIGHER_EDUCATION','PRIMARY_SECONDARY_EDUCATION','RESEARCH','LIBRARIES') THEN 'Education & Training'
        ELSE NULL
    END AS industry_group,
    b.CATEGORY AS event_type,
    CASE WHEN YEAR(b.META__CREATEDAT) IN (2022, 2023) THEN 'before' ELSE 'after' END AS period,
    COUNT(*) AS cnt
FROM HIRE_SPACE.CORE_DATA.BOOKINGS b
JOIN HIRE_SPACE.CORE_DATA.COMPANIES c ON c."_ID" = b."COMPANYDATA___ID"
JOIN SEGMENT_EVENTS.HUBSPOT.COMPANIES hc ON hc.HS_OBJECT_ID = c.HUBSPOTID
WHERE YEAR(b.META__CREATEDAT) BETWEEN 2022 AND 2025
  AND hc.INDUSTRY IS NOT NULL
  AND b.CATEGORY IS NOT NULL
GROUP BY 1, 2, 3
HAVING industry_group IS NOT NULL
ORDER BY 1, 4 DESC;

-- ── Post-processing (Python) ──
-- For each industry:
--   share = category_count / industry_total * 100
--   change = after_share - before_share
-- Top 4 gaining (change > 0, sorted desc) and top 3 declining (change < 0, sorted asc)
-- Results stored in js/data.js under DATA.eventTypesByIndustry
